### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by genixpro** [Yonaba/Moses#30]
sudo luarocks install moses

Installing https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/moses-1.6.0-1.rockspec...
Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/moses-1.6.0-1.rockspec... switching to 'build' mode

Error: Directory Moses-Moses-1.0.0-1 not found inside archive Moses-1.6.0-1.tar.gz

**Comment by denisdemaisbr** [comment]
all releases can be found at  -> https://github.com/Yonaba/Moses/releases

**Comment by Yonaba** [comment]
Hi, @genixpro
Yes I see what happened. The rockspec for 1.6.0 initially had an issue. I fixed it, but it were not were not updated on moonrocks-mirror.
I just tried to delete the rockspec from LuaRocks and then pushing it back again. It should normally trigger the moonrocks-uploader, and push the new rockspec in moonrocks-mirror. Hopefully. Let me know.

Otherwise, you can still grab the good rockspec straight at [LuaRocks](http://luarocks.org/modules/yonaba/moses/1.6.0-1).

**Comment by chongw** [comment]
Hi @Yonaba ,

Thanks for the updates. But it still triggers this.

---
Installing https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/moses-1.6.0-1.rockspec...
Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/moses-1.6.0-1.rockspec... switching to 'build' mode

Error: Directory Moses-Moses-1.0.0-1 not found inside archive Moses-1.6.0-1.tar.gz
-----

**Comment by Yonaba** [comment]
@genixpro and @chongw, the backup mirror on moonrocks [have been kindly updated](https://github.com/rocks-moonscript-org/moonrocks-mirror/commit/04a4580d96a784ea2a6d2286971f07758ae644f5) by @leafo. Would you please give it a try and let me know if it works for you ?

**Comment by chongw** [comment]
@Yonaba and @genixpro , it works great this time. thanks!

**Comment by leafo** [comment]
Any reason why you're hitting the mirror instead of luarocks.org when you install?

**Comment by Yonaba** [comment]
@leafo is right. As said in the README, a simple ````luarocks install moses```` would do.
